import { VocabularyCard } from "../types";

export const wordStore: VocabularyCard[] = [
	{
		id: 0,
		name: "Basic essentials",
		dateCreated: "01/04/2025",
		progress: 0,
		words: [
			{
				id: 1,
				originalWord: "hello",
				translations: "привіт",
				note: "Common greeting",
			},
			{ id: 2, originalWord: "goodbye", translations: "до побачення" },
			{ id: 3, originalWord: "thank you", translations: "дякую" },
			{ id: 4, originalWord: "please", translations: "будь ласка" },
			{ id: 5, originalWord: "yes", translations: "так" },
			{ id: 6, originalWord: "no", translations: "ні" },
			{
				id: 7,
				originalWord: "sorry",
				translations: "вибачте",
				note: "Formal apology",
			},
		],
	},
	{
		id: 1,
		name: "Family and Home",
		dateCreated: "01/04/2025",
		progress: 0,
		words: [
			{ id: 8, originalWord: "friend", translations: "друг" },
			{ id: 9, originalWord: "family", translations: "сім'я" },
			{ id: 10, originalWord: "home", translations: "дім" },
			{ id: 11, originalWord: "school", translations: "школа" },
			{ id: 12, originalWord: "work", translations: "робота" },
			{ id: 13, originalWord: "water", translations: "вода" },
			{
				id: 14,
				originalWord: "food",
				translations: "їжа",
				note: "Essential for survival",
			},
		],
	},
	{
		id: 2,
		name: "Time and Dates",
		dateCreated: "01/04/2025",
		progress: 0,
		words: [
			{ id: 15, originalWord: "time", translations: "час" },
			{ id: 16, originalWord: "day", translations: "день" },
			{ id: 17, originalWord: "night", translations: "ніч" },
			{ id: 18, originalWord: "week", translations: "тиждень" },
			{ id: 19, originalWord: "month", translations: "місяць" },
			{ id: 20, originalWord: "year", translations: "рік" },
			{
				id: 21,
				originalWord: "man",
				translations: "чоловік",
				note: "Adult male",
			},
		],
	},
	{
		id: 3,
		name: "People and Places",
		dateCreated: "01/04/2025",
		progress: 0,
		words: [
			{ id: 22, originalWord: "woman", translations: "жінка" },
			{ id: 23, originalWord: "child", translations: "дитина" },
			{ id: 24, originalWord: "city", translations: "місто" },
			{ id: 25, originalWord: "country", translations: "країна" },
			{ id: 26, originalWord: "language", translations: "мова" },
			{ id: 27, originalWord: "book", translations: "книга" },
			{
				id: 28,
				originalWord: "pen",
				translations: "ручка",
				note: "Used for writing",
			},
		],
	},
	{
		id: 4,
		name: "Nature and Environment",
		dateCreated: "01/04/2025",
		progress: 0,
		words: [
			{ id: 29, originalWord: "door", translations: "двері" },
			{ id: 30, originalWord: "window", translations: "вікно" },
			{ id: 31, originalWord: "tree", translations: "дерево" },
			{ id: 32, originalWord: "flower", translations: "квітка" },
			{ id: 33, originalWord: "sun", translations: "сонце" },
			{ id: 34, originalWord: "moon", translations: "місяць" },
			{
				id: 35,
				originalWord: "star",
				translations: "зірка",
				note: "In the sky at night",
			},
		],
	},
];
